"""Remove previous sample records and persist real dashboards and telemetry."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "004_real_workspaces"
down_revision = "003_triggers_views"
branch_labels = None
depends_on = None


def upgrade():
    # Only the exact rows generated by the former automatic sample-data seeder.
    # Any account registered by an actual user is never touched.
    op.execute("DELETE FROM alert_history WHERE project_id IN (SELECT id FROM projects WHERE name IN ('Monitoring Kebun Greenhouse', 'Smart Home Siti', 'Smart Smart-Home Siti'))")
    op.execute("DELETE FROM projects WHERE name IN ('Monitoring Kebun Greenhouse', 'Smart Home Siti', 'Smart Smart-Home Siti')")
    op.execute("DELETE FROM accounts WHERE lower(email) IN ('pak-ahmad@example.com', 'bu-siti@example.com')")
    op.create_table(
        "project_dashboards",
        sa.Column("project_id", sa.BigInteger(), primary_key=True),
        sa.Column("widgets", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
    )
    op.create_table(
        "telemetry_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("device_id", sa.BigInteger(), nullable=False),
        sa.Column("protocol", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_telemetry_events_project_received", "telemetry_events", ["project_id", "received_at"])


def downgrade():
    op.drop_index("ix_telemetry_events_project_received", table_name="telemetry_events")
    op.drop_table("telemetry_events")
    op.drop_table("project_dashboards")
